version: '3'


services:
  phala-worker-pruntime:
    image: swr.cn-east-3.myhuaweicloud.com/phala/phala-poc4-pruntime
    container_name: phala-pruntime
    volumes:
      - /opt/phala/phala-pruntime-data:/root/data
    #    stdin_open: true
    restart: always
    tty: true
    # -------------- SGX 驱动 和 DCAP 驱动 二选一，根据机器驱动进行选择注释
    # -------------- SGX 驱动 --------------
    devices:
      - "/dev/isgx:/dev/isgx"
    # -------------- DCAP 驱动 --------------
#    devices:
#      - "/dev/sgx/enclave:/dev/sgx/enclave"
#      - "/dev/sgx/provision:/dev/sgx/provision"
    ports:
      - "8000:8000"
    expose:
      # Opens port 8000 on the container
      - '8000'

  phala-worker-phost:
    image: swr.cn-east-3.myhuaweicloud.com/phala/phala-poc4-phost
    container_name: phala-phost
    #    stdin_open: true
    restart: always
    tty: true
    volumes:
      - "../phost_start:/phost_start"
    environment:
      - PRUNTIME_ENDPOINT=http://phala-pruntime:8000
      - PHALA_NODE_WS_ENDPOINT=ws://{master_ip}:9944
      - MNEMONIC=mobile xxx machine carry snow xxx route narrow xxx basic dial xxx
      - EXTRA_OPTS= -r
      - SLEEP_BEFORE_START=0
    command: /phost_start