version: "3"
services:
 phala-pruntime:
   image: ${PRUNTIME_IMAGE}
   container_name: phala-pruntime
   hostname: phala-pruntime
   ports:
    - "8000:8000"
   devices:
      - /dev/sgx/enclave
      - /dev/sgx/provision
      - /dev/sgx_enclave
      - /dev/sgx_provision

   environment:
    - EXTRA_OPTS=--cores=${CORES}
    - ROCKET_ADDRESS=0.0.0.0
   volumes:
    - ${PRUNTIME_VOLUMES}

 phala-pherry:
   image: ${PHERRY_IMAGE}
   container_name: phala-pherry
   hostname: phala-pherry
   depends_on:
    - phala-pruntime
   restart: always
   entrypoint:
    [
      "/root/pherry",
      "-r",
      "--parachain",
      "--mnemonic=${MNEMONIC}",
      "--substrate-ws-endpoint=ws://${MASTER_IP}:9945",
      "--collator-ws-endpoint=ws://${MASTER_IP}:9944",
      "--pruntime-endpoint=http://phala-pruntime:8000",
      "--operator=${OPERATOR}",
      "--fetch-blocks=512",
    ]
